### ISSUE TITLE
Doesn't work on Android 10

### ISSUE THREAD

**Issue by nitanmarcel** [refi64/cloverplay#1]
Is this project discontinued? There haven't been any updates for a while and it doesn't seem to work for me on Android 10. I can toggle the service on but when opening GFN no overlay is shown. I've enabled GFN support in settings.

Tell me if you need logcat or anything.

Thanks.

**Comment by refi64** [comment]
Unfortunately, mostly :sweat_smile: I don't even use a rooted device as my daily driver, and Stadia is...yeah.

That being said, I'm *moderately* sure I used to use this back on Android 10. Does your device have root?

**Comment by nitanmarcel** [comment]
> Unfortunately, mostly sweat_smile I don't even use a rooted device as my daily driver, and Stadia is...yeah.
> 
> That being said, I'm _moderately_ sure I used to use this back on Android 10. Does your device have root?

Could be just because how I use android: In an lxc container on a linux phone, and I suppose something doesn't get sent to the app to tell it that an something was done. idk.

Now I'm using Android 11, is it supposed to work there?

**Comment by refi64** [comment]
> Now I'm using Android 11, is it supposed to work there?

I'm moderately sure that I did use this successfully on Android 11. I can *definitely* say that an LXC container probably wouldn't work, because this specifically relies on Android's accessibility API to draw over the apps, and that's probably not emulated fully/properly in the LXC case.

**Comment by nitanmarcel** [comment]
> > Now I'm using Android 11, is it supposed to work there?
> 
> I'm moderately sure that I did use this successfully on Android 11. I can _definitely_ say that an LXC container probably wouldn't work, because this specifically relies on Android's accessibility API to draw over the apps, and that's probably not emulated fully/properly in the LXC case.

Drawing over apps seem to work fine too

https://play.google.com/store/apps/details?id=com.github.ericytsang.screenfilter.app.android&pli=1


![Screenshot_2023_01_07_08_35_24](https://user-images.githubusercontent.com/41646249/211141668-6538481f-4c9a-4b91-9740-e3afd4cd803e.jpg)

**Comment by nitanmarcel** [comment]
Works fine on pure android, I guess the waydroid app I was using on my Linux phone was the issue. Anyway it also seems that GeForce Now which I was playing finally has touch controls on Android
